#!/bin/bash

cat <<\EOD
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////////////////////////////////////////////////////
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

RetroStar Client-Installation
EOD

is_ssh_process() {
    local pid=$1
    local comm
    read -r comm < "/proc/$pid/comm"
    [ "$comm" == "sshd" ]
}

is_ssh6_connection() {
    local pid=$$
    while [ $pid -ne 1 ]; do
        read -r _ _ _ ppid _ < "/proc/$pid/stat"
        if is_ssh_process "$ppid"; then
            if lsof -p "$ppid" | awk '$5 == "IPv6" { exit 1 }'; then
                return 1
            else
                return 0
            fi
        fi
        pid=$ppid
    done
    return 1 # Return false if no SSH daemon is found
}

if is_ssh6_connection; then
    cat <<EOD

Du bist über IPv6 mit dem Raspberry Pi verbunden.  Da IPv6 im Verlauf der
Installation abgeschaltet wird, musst Du Dich mit IPv4 verbinden oder die
Einrichtung auf der Konsole machen.  Unter Linux geht das mit dem Befehl

        ssh -4 $(hostname)

Die Installation wird abgebrochen.
EOD
    exit 1
fi


if ! ip a | grep -q ': eth0:'
then
    cat <<\EOD

Es wurde kein Ethernet-Interface mit dem Namen "eth0" gefunden.  Es kann sein,
dass es unter einem anderen Namen angelegt wurde.  Zur Korrektur dann wie folgt
vorgehen:

sudo raspi-config

"Advanced Options" auswählen
"Network Interface Names" auswählen
"Would you like to enable predictable network interface names?" mit "Yes" beantworten.

"Finish" auswählen und die Frage nach Reboot mit "Yes" beantworten.

Dann diese Installation neu starten.
EOD
    exit 1
fi

if ip r | grep -q '^default.* eth0 '
then
    cat <<\EOD

Der Raspberry Pi hat eine Default-Route auf dem Ethernet-Interface.
Für den Betrieb mit RetroStar muss die Internetverbindung über WLAN
hergestellt werden.  Auf dem Ethernet-Interface muss IP abgeschaltet
werden.  In älteren Betriebssystemversionen geht das, indem die Zeile

denyinterfaces eth0

am Anfang der Datei /etc/dhcpcd.conf eingefügt wird.  In bookworm oder
später kann es durch den Befehl

sudo nmcli dev disconnect iface eth0

abgeschaltet werden.

Starte den Pi nach der Konfigurationsänderung neu und versuche diese
Installation dann noch einmal.
EOD
    exit 1
fi

cat <<\EOD

Dieses Paket installiert den RetroStar-Client.  Du benötigst Deinen persönlichen
Installationsschlüssel, den Du auf

      https://retrostar.classic-computing.de/installation

abrufen kannst.

ACHTUNG: Die Netzwerkkonfiguration wird entsprechend den Erfordernissen der
OpenVPN-Bridge angepasst.  IPv6 wird komplett abgeschaltet und eine virtuelle
Bridge eingerichtet, die das Ethernet des Pi transparent mit dem gemeinsamen
Retro-LAN verbindet.  IP-Pakete werden nicht weitergeleitet, aber es empfiehlt
sich dennoch, auf dem Ethernet keine wichtigen Dinge zu machen, da über die
Bridge allerlei bunter Verkehr hereinkommen kann.

Wenn Du nicht fortfahren möchtest, kannst Du die Installation mit Ctrl-C
abbrechen.

////////////////////////////////////////////////////////////////////////////////
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
////////////////////////////////////////////////////////////////////////////////

EOD

token_regex='^[a-zA-Z0-9]{4}-[a-zA-Z0-9]{4}$'

while true; do
    read -rp "Gib Deinen Installationsschlüssel ein (Abbruch mit ENTER): " token
    if [[ $token == "" ]]; then
        echo "Installation abgebrochen"
        exit 1
    fi
    if [[ ! $token =~ $token_regex ]]; then
        echo "Ungültiges Format."
        continue
    fi
    mkdir -p /etc/retrostar
    if curl --silent --fail -Lo /etc/retrostar/openvpn.conf https://retrostar.classic-computing.de/client-config/"$token"
    then
        break
    else
        echo "Ungültiger Installationsschlüssel."
    fi
done

cat <<\EOD

Deine Konfiguration wurde unter /etc/retrostar/openvpn.conf gespeichert
EOD
